//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSProviderSpec.
func (in *AWSProviderSpec) DeepCopy() *AWSProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AWSProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotNetworkPolicySpec.
func (in *BotNetworkPolicySpec) DeepCopy() *BotNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(BotNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotNetworkPolicyStatus.
func (in *BotNetworkPolicyStatus) DeepCopy() *BotNetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(BotNetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapProviderSpec) DeepCopyInto(out *ConfigMapProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapProviderSpec.
func (in *ConfigMapProviderSpec) DeepCopy() *ConfigMapProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigMapProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldCondition.
func (in *FieldCondition) DeepCopy() *FieldCondition {
	if in == nil {
		return nil
	}
	out := new(FieldCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubProviderSpec.
func (in *GitHubProviderSpec) DeepCopy() *GitHubProviderSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleProviderSpec.
func (in *GoogleProviderSpec) DeepCopy() *GoogleProviderSpec {
	if in == nil {
		return nil
	}
	out := new(GoogleProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHeaderSecretRef.
func (in *HTTPHeaderSecretRef) DeepCopy() *HTTPHeaderSecretRef {
	if in == nil {
		return nil
	}
	out := new(HTTPHeaderSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONEndpointProviderSpec.
func (in *JSONEndpointProviderSpec) DeepCopy() *JSONEndpointProviderSpec {
	if in == nil {
		return nil
	}
	out := new(JSONEndpointProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONFilterSpec.
func (in *JSONFilterSpec) DeepCopy() *JSONFilterSpec {
	if in == nil {
		return nil
	}
	out := new(JSONFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}
